---
/thruster_manager:
  ros__parameters:
    # Columns correspond to each thruster in order:
    # FRH, FLH, BRH, BLH, FRV, FLV, BRV, BLV
    tam:
      x:  [.86602540378, 0.86602540378,  0.86602540378,  0.86602540378,0.0,      0.0,      0.0,      0.0     ]
      y:  [0.5,           -0.5,           -0.5,           0.5,          0.0,      0.0,      0.0,      0.0     ]
      z:  [0.0,           0.0,            0.0,            0.0,          1.0,      1.0,      1.0,      1.0     ]
      rx: [0.0,           0.0,            0.0,            0.0,          -0.14922,  0.14922,  -0.14922,  0.14922 ] # roll
      ry: [0.0,           0.0,            0.0,            0.0,          -0.230185, -0.230185, 0.230185,0.231085] # pitch
      rz: [0.2695308,     -0.2695308,     0.337687697,  -0.337687697,   0.0,      0.0,      0.0,      0.0     ] # yaw
    thruster_cap: 1.0
    max_force_pos: 51.5
    max_force_neg: 39.9
